"""change fks to match back_populate

Revision ID: c9afdf013459
Revises: 32cac12d29be
Create Date: 2021-01-27 17:29:39.783920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9afdf013459'
down_revision = '32cac12d29be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
